module.exports = {
  transparent: 'transparent',
  current: 'currentColor',
  rorange: {
    20: 'var(--elv-color-rorange-20)',
    40: 'var(--elv-color-rorange-40)',
    60: 'var(--elv-color-rorange-60)',
    80: 'var(--elv-color-rorange-80)',
    100: 'var(--elv-color-rorange-100)',
    DEFAULT: 'var(--elv-color-rorange-100)',
    120: 'var(--elv-color-rorange-120)',
    140: 'var(--elv-color-rorange-140)',
    160: 'var(--elv-color-rorange-160)',
    180: 'var(--elv-color-rorange-180)',
  },
  purple: {
    5: 'var(--elv-color-purple-5)',
    10: 'var(--elv-color-purple-10)',
    20: 'var(--elv-color-purple-20)',
    30: 'var(--elv-color-purple-30)',
    40: 'var(--elv-color-purple-40)',
    60: 'var(--elv-color-purple-60)',
    80: 'var(--elv-color-purple-80)',
    100: 'var(--elv-color-purple-100)',
    DEFAULT: 'var(--elv-color-purple-100)',
    120: 'var(--elv-color-purple-120)',
    140: 'var(--elv-color-purple-140)',
    160: 'var(--elv-color-purple-160)',
    180: 'var(--elv-color-purple-180)',
  },
  blue: {
    20: 'var(--elv-color-blue-20)',
    40: 'var(--elv-color-blue-40)',
    60: 'var(--elv-color-blue-60)',
    80: 'var(--elv-color-blue-80)',
    100: 'var(--elv-color-blue-100)',
    DEFAULT: 'var(--elv-color-blue-100)',
    120: 'var(--elv-color-blue-120)',
    140: 'var(--elv-color-blue-140)',
    160: 'var(--elv-color-blue-160)',
    180: 'var(--elv-color-blue-180)',
  },
  green: {
    20: 'var(--elv-color-green-20)',
    40: 'var(--elv-color-green-40)',
    60: 'var(--elv-color-green-60)',
    80: 'var(--elv-color-green-80)',
    100: 'var(--elv-color-green-100)',
    DEFAULT: 'var(--elv-color-green-100)',
    120: 'var(--elv-color-green-120)',
    140: 'var(--elv-color-green-140)',
    160: 'var(--elv-color-green-160)',
    180: 'var(--elv-color-green-180)',
  },
  yellow: {
    20: 'var(--elv-color-yellow-20)',
    40: 'var(--elv-color-yellow-40)',
    60: 'var(--elv-color-yellow-60)',
    80: 'var(--elv-color-yellow-80)',
    100: 'var(--elv-color-yellow-100)',
    DEFAULT: 'var(--elv-color-yellow-100)',
    120: 'var(--elv-color-yellow-120)',
    140: 'var(--elv-color-yellow-140)',
    160: 'var(--elv-color-yellow-160)',
    180: 'var(--elv-color-yellow-180)',
  },
  primary: {
    5: 'var(--elv-bg-primary-5)',
    10: 'var(--elv-bg-primary-10)',
    20: 'var(--elv-bg-primary-20)',
    30: 'var(--elv-bg-primary-30)',
    40: 'var(--elv-bg-primary-40)',
    60: 'var(--elv-bg-primary-60)',
    80: 'var(--elv-bg-primary-80)',
    DEFAULT: 'var(--elv-bg-primary)',
    120: 'var(--elv-bg-primary-120)',
  },
  neutral: {
    0: 'var(--elv-bg-neutral-0)',
    1: 'var(--elv-bg-neutral-1)',
    5: 'var(--elv-bg-neutral-5)',
    10: 'var(--elv-bg-neutral-10)',
    20: 'var(--elv-bg-neutral-20)',
    30: 'var(--elv-color-neutral-30)',
    DEFAULT: 'var(--elv-bg-neutral)',
    40: 'var(--elv-bg-neutral-40)',
    50: 'var(--elv-color-neutral-50)',
    70: 'var(--elv-color-neutral-70)',
    80: 'var(--elv-color-neutral-80)',
    90: 'var(--elv-color-neutral-90)',
    100: 'var(--elv-bg-neutral-100)',
  },
  info: {
    20: 'var(--elv-bg-info-20)',
    DEFAULT: 'var(--elv-bg-info)',
  },
  critical: {
    20: 'var(--elv-bg-critical-20)',
    40: 'var(--elv-bg-critical-40)',
    DEFAULT: 'var(--elv-bg-critical)',
    140: 'var(--elv-bg-critical-140)',
  },
  warning: {
    20: 'var(--elv-bg-warning-20)',
    DEFAULT: 'var(--elv-bg-warning)',
  },
  success: {
    20: 'var(--elv-bg-success-20)',
    40: 'var(--elv-bg-success-40)',
    DEFAULT: 'var(--elv-bg-success)',
  },
  brand: {
    DEFAULT: 'var(--elv-bg-brand)',
  },
  inverted: {
    DEFAULT: 'var(--elv-bg-inverted)',
  },
};
