module.exports = {
  transparent: 'transparent',
  current: 'currentColor',
  rorange: {
    20: 'var(--elv-color-rorange-20)',
    40: 'var(--elv-color-rorange-40)',
    60: 'var(--elv-color-rorange-60)',
    80: 'var(--elv-color-rorange-80)',
    100: 'var(--elv-color-rorange-100)',
    DEFAULT: 'var(--elv-color-rorange-100)',
    120: 'var(--elv-color-rorange-120)',
    140: 'var(--elv-color-rorange-140)',
    160: 'var(--elv-color-rorange-160)',
    180: 'var(--elv-color-rorange-180)',
  },
  purple: {
    5: 'var(--elv-color-purple-5)',
    10: 'var(--elv-color-purple-10)',
    20: 'var(--elv-color-purple-20)',
    30: 'var(--elv-color-purple-30)',
    40: 'var(--elv-color-purple-40)',
    60: 'var(--elv-color-purple-60)',
    80: 'var(--elv-color-purple-80)',
    100: 'var(--elv-color-purple-100)',
    DEFAULT: 'var(--elv-color-purple-100)',
    120: 'var(--elv-color-purple-120)',
    140: 'var(--elv-color-purple-140)',
    160: 'var(--elv-color-purple-160)',
    180: 'var(--elv-color-purple-180)',
  },
  blue: {
    20: 'var(--elv-color-blue-20)',
    40: 'var(--elv-color-blue-40)',
    60: 'var(--elv-color-blue-60)',
    80: 'var(--elv-color-blue-80)',
    100: 'var(--elv-color-blue-100)',
    DEFAULT: 'var(--elv-color-blue-100)',
    120: 'var(--elv-color-blue-120)',
    140: 'var(--elv-color-blue-140)',
    160: 'var(--elv-color-blue-160)',
    180: 'var(--elv-color-blue-180)',
  },
  green: {
    20: 'var(--elv-color-green-20)',
    40: 'var(--elv-color-green-40)',
    60: 'var(--elv-color-green-60)',
    80: 'var(--elv-color-green-80)',
    100: 'var(--elv-color-green-100)',
    DEFAULT: 'var(--elv-color-green-100)',
    120: 'var(--elv-color-green-120)',
    140: 'var(--elv-color-green-140)',
    160: 'var(--elv-color-green-160)',
    180: 'var(--elv-color-green-180)',
  },
  yellow: {
    20: 'var(--elv-color-yellow-20)',
    40: 'var(--elv-color-yellow-40)',
    60: 'var(--elv-color-yellow-60)',
    80: 'var(--elv-color-yellow-80)',
    100: 'var(--elv-color-yellow-100)',
    DEFAULT: 'var(--elv-color-yellow-100)',
    120: 'var(--elv-color-yellow-120)',
    140: 'var(--elv-color-yellow-140)',
    160: 'var(--elv-color-yellow-160)',
    180: 'var(--elv-color-yellow-180)',
  },
  whisper: {
    DEFAULT: 'var(--elv-border-whisper)',
  },
  light: {
    DEFAULT: 'var(--elv-border-light)',
  },
  medium: {
    DEFAULT: 'var(--elv-border-medium)',
  },
  dark: {
    DEFAULT: 'var(--elv-border-dark)',
  },
  inverted: {
    DEFAULT: 'var(--elv-border-inverted)',
  },
  neutral: {
    0: 'var(--elv-color-neutral-0)',
    1: 'var(--elv-color-neutral-1)',
    5: 'var(--elv-color-neutral-5)',
    10: 'var(--elv-color-neutral-10)',
    20: 'var(--elv-color-neutral-20)',
    30: 'var(--elv-color-neutral-30)',
    40: 'var(--elv-color-neutral-40)',
    50: 'var(--elv-color-neutral-50)',
    60: 'var(--elv-color-neutral-60)',
    70: 'var(--elv-color-neutral-70)',
    80: 'var(--elv-color-neutral-80)',
    90: 'var(--elv-color-neutral-90)',
    DEFAULT: 'var(--elv-border-neutral)',
    100: 'var(--elv-color-neutral-100)',
  },
  info: {
    DEFAULT: 'var(--elv-border-info)',
  },
  success: {
    DEFAULT: 'var(--elv-border-success)',
  },
  critical: {
    DEFAULT: 'var(--elv-border-critical)',
  },
  warning: {
    DEFAULT: 'var(--elv-border-warning)',
  },
  primary: {
    DEFAULT: 'var(--elv-border-primary)',
  },
  focus: {
    DEFAULT: 'var(--elv-border-focus)',
  },
  'data-secondary-1': {
    DEFAULT: 'var(--elv-border-data-secondary-1)',
  },
};
